docker:
    path: .
id: bfeaa8a1-7aaa-45ca-b4b4-145edafdee4e
ide:
    filename: ide.yaml
name: dbt-testing-hackaton
resources:
    path: resources
streaming:
    filename: streaming.yaml
template: ""
version: "0.3"
workflows:
    path: dags
    version: "2"
